set(CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake") # NECESSARY, OTHERWISE OUR MacoOSXBundleInfo.plist.in IS NOT PICKED
set(CMAKE_MACOSX_BUNDLE YES) # NECESSARY, OTHERWISE add_executable() IN CMakeLists.txt WON'T HAVE ANY EFFECT

set(CMAKE_OSX_SYSROOT iphoneos)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "iPhone Developer")

set(CMAKE_OSX_ARCHITECTURES "armv7;arm64")
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO) # NECESSARY, OTHERWISE arm64 ARCH WON'T BE INCLUDED

set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET 6.0)
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++") # NECESSARY WHEN DEPLOYMENT TARGET IS BELOW 7.0

set(MACOSX_BUNDLE_GUI_IDENTIFIER "org.chronotext.HelloGTest")
set(MACOSX_BUNDLE_EXECUTABLE_NAME HelloGTest)
